from empleado import Empleado
from administrativo import Administrativo
from ingenierotecnico import IngenieroTecnico
from operario import Operario
from administradoralmacen import AdministradorAlmacen
from elemento import Elemento

def empleadosFicticios(empleados):

    e1 = AdministradorAlmacen()
    e1.setIdent(70900191)
    e1.setNombre("Alejandro")
    e1.setApellido("Arbelaez Montoya")
    e1.setNumElementPres(0)
    e1.setRoll(Empleado().tiposEmpleado['1'])
    e1.setEmail("aarbelaez1@misena.edu.co")
    e1.setGrado(10)
    e1.setUsuario("aarbelaez1")
    e1.setPassword("70900191")
    empleados.append(e1)

    e2 = AdministradorAlmacen()
    e2.setIdent(1113040465)
    e2.setNombre("Jaime Orlando")
    e2.setApellido("Cardenas Crespo")
    e2.setNumElementPres(0)
    e2.setRoll(Empleado().tiposEmpleado['1'])
    e2.setEmail("jocardenas5@misena.edu.co")
    e2.setGrado(10)
    e2.setUsuario("jocardenas5")
    e2.setPassword("1113040465")
    empleados.append(e2)

    e3 = Administrativo()
    e3.setIdent(98670551)
    e3.setNombre("Juan Carlos")
    e3.setApellido("Calle Garzon")
    e3.setNumElementPres(0)
    e3.setRoll(Empleado().tiposEmpleado['2'])
    e3.setEmail("jccalle@misena.edu.co")
    e3.setGrado(10)
    empleados.append(e3)

    e4 = IngenieroTecnico()
    e4.setIdent(43098368)
    e4.setNombre("Liliana Maria")
    e4.setApellido("Carmona Molano")
    e4.setNumElementPres(0)
    e4.setRoll(Empleado().tiposEmpleado['3'])
    e4.setEmail("lmcarmona86@misena.edu.co")
    e4.setArea("Produccion")
    empleados.append(e4)

    e5 = Operario()
    e5.setIdent(75147008)
    e5.setNombre("Carlos Andres")
    e5.setApellido("Correa Diaz")
    e5.setNumElementPres(0)
    e5.setRoll(Empleado().tiposEmpleado['4'])
    e5.setEmail("ccorrea78@misena.edu.co")
    e5.setTipo("Mecanico")
    empleados.append(e5)

def elementosFicticios(elementos):

    elemento1 = Elemento()
    elemento1.setCodigo(3824)
    elemento1.setDescripcion("Taladro Percutor")
    elemento1.setModelo("BP984")
    elemento1.setMarca("Bosh")
    elemento1.setUbicacion("A5")
    elemento1.setFechaPrestamo(None)
    elemento1.setValor(700000)
    elemento1.setEstadoActual(Elemento().estados['1'])
    elementos.append(elemento1)

    elemento2 = Elemento()
    elemento2.setCodigo(4258)
    elemento2.setDescripcion("Monitor LED")
    elemento2.setModelo("SA4528")
    elemento2.setMarca("Samsung")
    elemento2.setUbicacion("B4")
    elemento2.setFechaPrestamo(None)
    elemento2.setValor(428000)
    elemento2.setEstadoActual(Elemento().estados['1'])
    elementos.append(elemento2)

    elemento3 = Elemento()
    elemento3.setCodigo(2520)
    elemento3.setDescripcion("Multimetro Digital")
    elemento3.setModelo("FD8747")
    elemento3.setMarca("Fluke")
    elemento3.setUbicacion("C1")
    elemento3.setFechaPrestamo(None)
    elemento3.setValor(699900)
    elemento3.setEstadoActual(Elemento().estados['1'])
    elementos.append(elemento3)

    elemento4 = Elemento()
    elemento4.setCodigo(2521)
    elemento4.setDescripcion("Fuente Regulada")
    elemento4.setModelo("UF9874")
    elemento4.setMarca("Uni-t")
    elemento4.setUbicacion("C2")
    elemento4.setFechaPrestamo(None)
    elemento4.setValor(589900)
    elemento4.setEstadoActual(Elemento().estados['1'])
    elementos.append(elemento4)